[package]
name = "projectorrs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
collection_macros = "0.2.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
